[package]
name = "drake-parser"
version = "0.0.1"
edition = "2021"

[dependencies]
# somen = "0.3"
somen = { git = "https://github.com/watcol/somen.git" }
drake-types = { path = "../drake-types/" }

[dev-dependencies]
futures-executor = "0.3"
